(function(){
'use strict';
const EMAIL='scottmcnamara316@gmail.com';
const WA='https://chat.whatsapp.com/DO6CyC5MwajLizwHNkmLHU?mode=gi_t';
const $=(s,c=document)=>c.querySelector(s); const $$=(s,c=document)=>Array.from(c.querySelectorAll(s));
function iconFallback(el){ if(el && el.parentElement){ el.parentElement.innerHTML='<i class="fa-solid fa-book-open"></i>'; } }
window.iconFallback=iconFallback;
const nav=[['home','الرئيسية','fa-house'],['masters','رسائل الماجستير والدكتوراه','fa-user-graduate'],['graduation-notes','مذكرات التخرج','fa-book'],['graduation-projects','مشاريع التخرج','fa-diagram-project'],['papers','الأوراق البحثية والمقالات','fa-file-lines'],['publishing','النشر الدولي والمحلي','fa-newspaper'],['translation','الترجمة وفحص الاقتباس','fa-language'],['statistics','التحليل الإحصائي','fa-chart-pie'],['programming','البرمجة والتطوير','fa-code'],['experts','خبراؤنا','fa-users'],['portfolio','أعمال سابقة','fa-briefcase'],['templates','المكتبة والقوالب','fa-folder-open'],['order-now','اطلب خدمتك الآن','fa-paper-plane']];
const features=[['fa-shield-halved','سرية كاملة','حماية بيانات العميل وتفاصيل المشروع، مع نماذج منظمة لتقليل الأخطاء.'],['fa-route','مسار واضح','ينتقل العميل من استعراض الخدمة إلى التسجيل ثم الطلب دون تعقيد.'],['fa-wand-magic-sparkles','تجربة جذابة','ألوان، حركة، بطاقات، وصور متجاوبة لتحسين الانطباع الأول.'],['fa-headset','متابعة مباشرة','إيميل وواتساب في كل نقاط التواصل المهمة داخل المنصة.']];
const specialtyImages={
'الطب':'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&q=80','الهندسة':'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400&q=80','العلوم':'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=400&q=80','الاجتماعية':'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&q=80','الإنسانية':'https://images.unsplash.com/photo-1491841573634-28140fc7ced7?w=400&q=80','الإدارة':'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&q=80','القانون':'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&q=80'};
const specialties=[['الطب',['الصحة العامة','التمريض','الصيدلة','المختبرات','طب الأسنان']],['الهندسة',['مدني','معماري','كهرباء','ميكانيك','برمجيات']],['العلوم',['كيمياء','فيزياء','أحياء','رياضيات','بيئة']],['الاجتماعية',['علم نفس','اجتماع','تربية','إعلام','خدمة اجتماعية']],['الإنسانية',['لغة عربية','تاريخ','فلسفة','آداب','ترجمة']],['الإدارة',['إدارة أعمال','محاسبة','تسويق','تمويل','اقتصاد']],['القانون',['قانون عام','قانون خاص','جنائي','دولي','تجاري']]];
const serviceImgs=[['الرسائل الجامعية','https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&q=80'],['النشر العلمي','https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600&q=80'],['الترجمة','https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&q=80'],['التحليل الإحصائي','https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80'],['فحص الاقتباس','https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&q=80'],['مشاريع التخرج','https://images.unsplash.com/photo-1523050854058-8df90910b683?w=600&q=80']];
const sections=[
{id:'masters',title:'رسائل الماجستير والدكتوراه',icon:'fa-user-graduate',grad:'linear-gradient(135deg,#1E3A5F,#2563EB)',desc:'خدمات متدرجة من اختيار الفكرة إلى المناقشة النهائية.',items:['اقتراح عنوان بحثي','كتابة بروبوزل','توفير مراجع ومصادر','تدقيق إملائي ولغوي','إعادة تنسيق حسب الدليل','كتابة فصل من الرسالة','إشراف كامل حتى التسليم','تحليل بيانات الرسالة','إعداد عرض المناقشة']},
{id:'graduation-notes',title:'مذكرات التخرج',icon:'fa-book-open',grad:'linear-gradient(135deg,#065F46,#10B981)',desc:'مساعدة عملية ومنظمة لطلاب البكالوريوس والليسانس.',items:['اقتراح موضوع مذكرة','إعداد خطة البحث','جمع مراجع حديثة','كتابة الإطار النظري','تنسيق نهائي للمذكرة','إعداد عرض المناقشة']},
{id:'graduation-projects',title:'مشاريع التخرج',icon:'fa-diagram-project',grad:'linear-gradient(135deg,#4C1D95,#7C3AED)',desc:'من الفكرة إلى النموذج النهائي والتقرير والعرض.',items:['اقتراح فكرة مشروع','تحليل المتطلبات','تنفيذ نموذج أولي','كتابة تقرير المشروع','إعداد العرض والشرح']},
{id:'papers',title:'الأوراق البحثية والمقالات',icon:'fa-file-lines',grad:'linear-gradient(135deg,#0E7490,#06B6D4)',desc:'خدمات بحثية للباحثين وطلاب الدراسات العليا.',items:['اقتراح عنوان مقال','كتابة ملخص أكاديمي','بناء منهجية الدراسة','تحرير أكاديمي ولغوي','تنسيق المراجع APA/Vancouver']},
{id:'publishing',title:'النشر الدولي والمحلي',icon:'fa-newspaper',grad:'linear-gradient(135deg,#1E3A5F,#2563EB)',desc:'خدمات تجهيز ومتابعة النشر العلمي.',items:['اختيار المجلة المناسبة','فحص شروط المجلة','تنسيق المقال حسب القالب','فحص الاقتباس وإعادة الصياغة','متابعة الرد على المحكمين'],publishing:true},
{id:'translation',title:'الترجمة وفحص الاقتباس',icon:'fa-language',grad:'linear-gradient(135deg,#B45309,#D97706)',desc:'ترجمة أكاديمية وفحص تشابه مع تحسين الصياغة.',items:['ترجمة عربية إنجليزية','ترجمة إنجليزية عربية','تدقيق لغوي أكاديمي','فحص نسبة الاقتباس','إعادة صياغة احترافية']},
{id:'statistics',title:'التحليل الإحصائي',icon:'fa-chart-pie',grad:'linear-gradient(135deg,#831843,#BE185D)',desc:'تحليل كمي ونوعي وتقارير نتائج قابلة للعرض.',items:['تصميم الاستبيان','إدخال وتنظيف البيانات','تحليل SPSS','تحليل R / Python','اختبارات الفرضيات','كتابة فصل النتائج']},
{id:'programming',title:'البرمجة والتطوير',icon:'fa-code',grad:'linear-gradient(135deg,#1E293B,#334155)',desc:'حلول برمجية تعليمية وبحثية ومشاريع تخرج.',items:['إنشاء مواقع ويب','تصميم واجهات UI','أنظمة إدارة','تطبيقات موبايل','مشاريع Python','مشاريع MATLAB','قواعد بيانات ولوحات تحكم']}
];
const journalLogos=['https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Scopus_logo.svg/320px-Scopus_logo.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Clarivate.svg/320px-Clarivate.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/US-NLM-PubMed-Logo.svg/320px-US-NLM-PubMed-Logo.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/DOI_logo.svg/320px-DOI_logo.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/ORCID_iD.svg/320px-ORCID_iD.svg.png','https://www.turnitin.com/img/turnitin-logo.svg'];
const intlJournals=Array.from({length:15},(_,i)=>({name:['Global Research Journal','International Academic Review','Science & Society Review','Engineering Research Letters','Medical Studies Journal'][i%5]+' '+(i+1),issn:`24${10+i}-99${20+i}`,logo:journalLogos[i%journalLogos.length]}));
const localJournals={
'الجزائر':['مجلة العلوم الإنسانية الجزائرية','مجلة الباحث الاقتصادي','مجلة دراسات قانونية','مجلة التربية والعلوم','مجلة الهندسة التطبيقية'],
'العراق':['مجلة جامعة بغداد','مجلة العلوم العراقية','مجلة القانون المقارن','مجلة الهندسة والتقنية','مجلة الإدارة والاقتصاد'],
'الأردن':['المجلة الأردنية للعلوم','دراسات الجامعة الأردنية','مجلة البلقاء للبحوث','مجلة القانون الأردنية','مجلة الأعمال الأردنية'],
'ليبيا':['مجلة الجامعات الليبية','المجلة الليبية للعلوم','مجلة الدراسات الإنسانية','مجلة القانون الليبية','مجلة الهندسة الليبية'],
'المغرب':['المجلة المغربية للبحث','مجلة العلوم القانونية','مجلة الاقتصاد المغربي','مجلة الآداب والعلوم','مجلة الهندسة المغربية']};
const expertMajors=['الطب','الهندسة','العلوم','الاجتماعية','الإنسانية','الإدارة','القانون'];
const countries=['السعودية','المغرب','الجزائر','العراق','الأردن','ليبيا','بريطانيا','أمريكا','فرنسا','ألمانيا','إسبانيا','إيطاليا','اليابان'];
const ranks=['ماسي','ذهبي','فضي','برونزي'];
const experts=[]; expertMajors.forEach((m,mi)=>{for(let i=1;i<=6;i++){experts.push({name:['د. سارة المنصور','أ.د. كريم العلي','د. مريم بن يوسف','د. جون ميلر','د. ليلى الهاشمي','د. ماركو روسي'][(i-1)%6],title:['أستاذ مشارك','محكم مجلات','خبير منهجية','مستشار بحثي','أستاذ مساعد','خبير تحليل'][i-1],major:m,country:countries[(mi*2+i)%countries.length],rating:(4.6+(i%4)*.1).toFixed(1),projects:35+mi*8+i*7,years:5+i+mi,rank:ranks[(i+mi)%4],bio:`خبرة في ${m}، مراجعة أكاديمية، منهجية بحث، ومتابعة مشاريع طلابية وبحثية.`})}});
const portfolio=['بحث PDF عن الإدارة الاستراتيجية','رسالة ماجستير في القانون','رسالة دكتوراه في التربية','مذكرة تخرج في المحاسبة','عرض تقديمي لمناقشة رسالة','مقال علمي في الطب','بحث PDF في الهندسة','رسالة ماجستير في علم النفس','مذكرة تخرج في الإعلام','عرض PPT لمشروع برمجي','مقال مراجعة أدبية','بحث في الاقتصاد','رسالة دكتوراه في العلوم','عرض مؤتمر علمي','مذكرة تخرج قانونية','بحث في الذكاء الاصطناعي'];
const templates=['قالب LaTeX رسالة ماجستير','قالب Word رسالة جامعية','قالب LaTeX ورقة بحثية','قالب Word مقال علمي','قالب عرض PowerPoint','قالب عرض مناقشة','قالب Cover Letter','قالب استبيان','قالب خطة بحث','قالب سيرة ذاتية أكاديمية','قالب تقرير مشروع تخرج','قالب ملخص بحثي'];
function renderHome(){
 if(!$('#sidebarLinks')) return;
 $('#sidebarLinks').innerHTML=nav.map(n=>`<a href="#${n[0]}" class="side-link"><i class="fa-solid ${n[2]}"></i>${n[1]}</a>`).join('');
 $('#featuresGrid').innerHTML=features.map((f,i)=>`<article class="feature-card" data-aos="fade-up" data-aos-delay="${i*70}"><div class="card-icon"><i class="fa-solid ${f[0]}"></i></div><h3>${f[1]}</h3><p>${f[2]}</p></article>`).join('');
 $('#specialtiesGrid').innerHTML=specialties.map((s,i)=>`<article class="specialty-card" data-aos="fade-up" data-aos-delay="${i*60}"><div class="specialty-img"><img loading="lazy" src="${specialtyImages[s[0]]}" onerror="iconFallback(this)" alt="${s[0]}"></div><div class="specialty-body"><h3>${s[0]}</h3><p>خدمات بحثية وتطبيقية حسب الفروع الدقيقة.</p><div class="chips">${s[1].map(x=>`<span>${x}</span>`).join('')}</div></div></article>`).join('');
 $('#serviceHighlightGrid').innerHTML=serviceImgs.map((s,i)=>`<article class="service-highlight" data-aos="fade-up" data-aos-delay="${i*60}"><div class="highlight-img"><img loading="lazy" src="${s[1]}" onerror="iconFallback(this)" alt="${s[0]}"></div><div class="body"><h3>${s[0]}</h3><p>خدمة منظمة ومهيأة حسب متطلبات الطالب أو الباحث.</p><button class="order-btn" data-service="${s[0]}">اطلب الخدمة</button></div></article>`).join('');
 $('#serviceSections').innerHTML=sections.map(sec=>renderServiceSection(sec)).join('');
 const filter=$('#expertFilter'); filter.innerHTML='<option value="all">كل التخصصات</option>'+expertMajors.map(m=>`<option value="${m}">${m}</option>`).join(''); renderExperts();
 $('#portfolioGrid').innerHTML=portfolio.map((x,i)=>`<article class="work-card" data-aos="fade-up"><div class="file-icon ${x.includes('عرض')?'ppt':''}"><i class="fa-solid ${x.includes('عرض')?'fa-file-powerpoint':'fa-file-pdf'}"></i></div><h3>${x}</h3><p class="muted">نموذج تعليمي قابل للاستبدال من ملفاتك الخاصة.</p><button class="download-btn" data-download="${x}"><i class="fa-solid fa-download"></i> تحميل</button></article>`).join('');
 $('#templatesGrid').innerHTML=templates.map((x,i)=>`<article class="template-card" data-aos="fade-up"><div class="file-icon ${x.includes('عرض')?'ppt':''}"><i class="fa-solid ${x.includes('عرض')?'fa-file-powerpoint':'fa-file-word'}"></i></div><h3>${x}</h3><p class="muted">قالب جاهز للاستخدام والتعديل.</p><button class="download-btn" data-download="${x}"><i class="fa-solid fa-download"></i> تحميل</button></article>`).join('');
 bindDynamicButtons(); initParticles(); if(window.AOS) AOS.init({duration:750,once:true,offset:60});
}
function renderServiceSection(sec){let html=`<section class="service-section" id="${sec.id}"><div class="section-banner" style="background:${sec.grad}" data-aos="fade-up"><i class="fa-solid ${sec.icon}"></i><div><h2>${sec.title}</h2><p>${sec.desc}</p></div></div><div class="services-grid">${sec.items.map((it,i)=>`<article class="service-card" data-aos="fade-up" data-aos-delay="${(i%3)*70}"><div class="card-icon"><i class="fa-solid ${sec.icon}"></i></div><h3>${it}</h3><p>نموذج طلب مخصص لهذه الخدمة مع حقول واضحة وتفاصيل قابلة للإرسال عبر الإيميل.</p><button class="order-btn" data-service="${it}">اطلب الآن</button></article>`).join('')}</div>`; if(sec.publishing) html+=renderPublishing(); return html+'</section>';}
function renderPublishing(){return `<div class="journals-wrap"><h3 class="sub-title"><i class="fa-solid fa-globe"></i> مجلات دولية مقترحة</h3><div class="journals-grid">${intlJournals.map(j=>`<article class="journal-card"><div class="journal-logo"><img loading="lazy" src="${j.logo}" onerror="iconFallback(this)" alt="${j.name}"></div><h4>${j.name}</h4><p>ISSN: ${j.issn}</p></article>`).join('')}</div><div class="country-block"><h3 class="sub-title"><i class="fa-solid fa-map-location-dot"></i> مجلات محلية حسب الدولة</h3><div class="country-tabs">${Object.keys(localJournals).map((c,i)=>`<button class="country-tab ${i===0?'active':''}" data-country="${c}">${c}</button>`).join('')}</div><div class="journals-grid" id="localJournalsGrid"></div></div></div>`}
function renderLocalJournals(country='الجزائر'){const g=$('#localJournalsGrid'); if(g) g.innerHTML=localJournals[country].map((n,i)=>`<article class="journal-card"><div class="journal-logo"><img loading="lazy" src="${journalLogos[i%journalLogos.length]}" onerror="iconFallback(this)" alt="${n}"></div><h4>${n}</h4><p>ISSN: ${2300+i}-${4500+i}</p></article>`).join('');}
function renderExperts(){const q=($('#expertSearch')?.value||'').trim().toLowerCase();const m=$('#expertFilter')?.value||'all';const data=experts.filter(e=>(m==='all'||e.major===m)&&[e.name,e.title,e.major,e.country,e.bio].join(' ').toLowerCase().includes(q));$('#expertsGrid').innerHTML=data.map(e=>`<article class="expert-card" data-aos="fade-up"><div class="expert-top"><div class="avatar">${e.name.split(' ').pop().slice(0,1)}</div><div><h3>${e.name}</h3><p>${e.title} - ${e.major} - ${e.country}</p><span class="badge ${e.rank}">${e.rank}</span></div></div><div class="expert-meta"><span><i class="fa-solid fa-star"></i> ${e.rating}</span><span>${e.projects} مشروع</span><span>${e.years} سنوات</span></div><p>${e.bio}</p></article>`).join('')||'<p class="muted">لا توجد نتائج.</p>';}
function bindDynamicButtons(){
 $$('.order-btn').forEach(btn=>btn.addEventListener('click',()=>openOrder(btn.dataset.service||'خدمة أكاديمية')));
 $$('.download-btn').forEach(btn=>btn.addEventListener('click',()=>{const title=btn.dataset.download;const blob=new Blob([`AcademiaHub\n${title}\nنموذج تجريبي قابل للاستبدال بملف حقيقي داخل المنصة.`],{type:'text/plain'}); const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=title.replace(/\s+/g,'_')+'.txt';a.click();URL.revokeObjectURL(a.href);}));
 $$('.country-tab').forEach(b=>b.addEventListener('click',()=>{$$('.country-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderLocalJournals(b.dataset.country)})); renderLocalJournals();
 $('#expertSearch')?.addEventListener('input',renderExperts); $('#expertFilter')?.addEventListener('change',renderExperts);
}
function openOrder(service){const user=JSON.parse(localStorage.getItem('ah_user')||'null'); if(!user){openAuth('register'); $('#authNote').textContent='سجّل أولاً حتى تتمكن من طلب الخدمة: '+service; sessionStorage.setItem('pendingService',service); return;} $('#orderTitle').textContent='طلب خدمة: '+service; $('#orderForm').dataset.service=service; const f=$('#orderForm'); if(f){f.name.value=user.name||'';f.email.value=user.email||'';f.major.value=user.major||'';f.level.value=user.level||'';} openModal('#orderModal');}
function openModal(sel){$(sel)?.classList.add('active');$(sel)?.setAttribute('aria-hidden','false')} function closeModal(sel){$(sel)?.classList.remove('active');$(sel)?.setAttribute('aria-hidden','true')}
function openAuth(tab='login'){openModal('#authModal'); switchAuth(tab)}
function switchAuth(tab){$$('.auth-tab').forEach(b=>b.classList.toggle('active',b.dataset.authTab===tab)); $$('.auth-form').forEach(f=>f.classList.remove('active')); $('#'+(tab==='register'?'registerForm':'loginForm'))?.classList.add('active');}
function setupCommon(){
 $('#openSidebar')?.addEventListener('click',()=>{$('#sidebar').classList.add('active');$('#sidebarOverlay').classList.add('active')});
 function closeSide(){$('#sidebar')?.classList.remove('active');$('#sidebarOverlay')?.classList.remove('active')} $('#closeSidebar')?.addEventListener('click',closeSide); $('#sidebarOverlay')?.addEventListener('click',closeSide); $$('.side-link').forEach(a=>a.addEventListener('click',closeSide));
 $$('[data-open-auth]').forEach(b=>b.addEventListener('click',()=>openAuth(b.dataset.openAuth))); $('#authClose')?.addEventListener('click',()=>closeModal('#authModal')); $('#orderClose')?.addEventListener('click',()=>closeModal('#orderModal'));
 $$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('active')})); $$('.auth-tab').forEach(b=>b.addEventListener('click',()=>switchAuth(b.dataset.authTab)));
 $('#registerForm')?.addEventListener('submit',e=>{e.preventDefault(); const u={name:$('#regName').value,email:$('#regEmail').value,level:$('#regLevel').value,major:$('#regMajor').value,password:$('#regPassword').value,createdAt:new Date().toISOString()}; localStorage.setItem('ah_user',JSON.stringify(u)); const pending=sessionStorage.getItem('pendingService'); if(pending){sessionStorage.removeItem('pendingService'); location.href='dashboard.html';}else{location.href='dashboard.html';}});
 $('#loginForm')?.addEventListener('submit',e=>{e.preventDefault(); const u=JSON.parse(localStorage.getItem('ah_user')||'null'); if(!u){$('#authNote').textContent='لا يوجد حساب محفوظ. أنشئ حساباً جديداً أولاً.'; $('#authNote').style.animation='shake .45s'; return;} location.href='dashboard.html';});
 $('#orderForm')?.addEventListener('submit',e=>{e.preventDefault(); submitOrder(new FormData(e.target), e.target.dataset.service||'خدمة أكاديمية'); closeModal('#orderModal');});
}
function genId(){return 'AH-'+Math.floor(100000+Math.random()*900000)}
function submitOrder(fd,service){const id=genId(); const now=new Date().toLocaleString('ar'); const data=Object.fromEntries(fd.entries()); const body=`رقم الطلب: ${id}\nالتاريخ والوقت: ${now}\nاسم العميل: ${data.name||''}\nالبريد: ${data.email||''}\nالهاتف: ${data.phone||''}\nنوع الخدمة: ${service||data.service||''}\nالمستوى: ${data.level||''}\nالتخصص: ${data.major||''}\nموعد التسليم: ${data.deadline||''}\n\nتفاصيل الطلب:\n${data.details||''}\n\nملاحظات إضافية:\n${data.notes||''}`; const subject='طلب خدمة جديد - '+id; window.open(`mailto:${EMAIL}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`,'_blank'); const orders=JSON.parse(localStorage.getItem('ah_orders')||'[]'); orders.unshift({id,service:service||data.service,date:now,details:data.details||'',major:data.major||''}); localStorage.setItem('ah_orders',JSON.stringify(orders)); alert(`✅ تم تقديم طلبك بنجاح\n\n📋 رقم الطلب: ${id}\n📧 سيتم التواصل عبر الإيميل\n📱 رابط الواتساب للمتابعة:\n${WA}`); renderDashboardOrders();}
function initParticles(){const canvas=$('#particles'); if(!canvas) return; const ctx=canvas.getContext('2d'); let w,h,parts=[]; function resize(){w=canvas.width=canvas.offsetWidth;h=canvas.height=canvas.offsetHeight;parts=Array.from({length:70},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*2+1,vx:(Math.random()-.5)*.45,vy:(Math.random()-.5)*.45}))} function draw(){ctx.clearRect(0,0,w,h);ctx.fillStyle='rgba(96,165,250,.75)';parts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();});requestAnimationFrame(draw)} resize();addEventListener('resize',resize);draw();}
function setupDashboard(){if(!document.body.classList.contains('dashboard-body')) return; const u=JSON.parse(localStorage.getItem('ah_user')||'null'); if(!u){location.href='index.html';return;} $('#clientName').textContent='مرحباً، '+u.name; $('#clientInfo').textContent=`${u.level} - ${u.major}`; $('#backHome')?.addEventListener('click',()=>location.href='index.html'); $('#logoutBtn')?.addEventListener('click',()=>{localStorage.removeItem('ah_user');location.href='index.html'}); const sel=$('#dashServiceSelect'); if(sel) sel.innerHTML=sections.flatMap(s=>s.items).map(x=>`<option>${x}</option>`).join(''); $('#dashOrderForm')?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target); fd.set('name',u.name);fd.set('email',u.email); submitOrder(fd,fd.get('service')); e.target.reset();}); renderDashboardOrders();}
function renderDashboardOrders(){const box=$('#savedOrders'); if(!box) return; const orders=JSON.parse(localStorage.getItem('ah_orders')||'[]'); $('#ordersCount').textContent=orders.length; box.innerHTML=orders.length?orders.map(o=>`<article class="saved-order"><strong>${o.id}</strong><p>${o.service} - ${o.major}</p><small>${o.date}</small></article>`).join(''):'<p class="muted">لا توجد طلبات محفوظة بعد.</p>';}
document.addEventListener('DOMContentLoaded',()=>{renderHome();setupCommon();setupDashboard();});
})();
